#include "renderer.hh"
#include "game.hh"

#include "mips.hh"

#define GLPROC(_name, _type) \
_type _name;
#include "gl_procs.inc"
#undef GLPROC

struct RendererFramebuffer {
    vec2 size;
    u32 video_memory;
    bool has_depth;
};

enum {
    RENDERER_FRAMEBUFFER_MAIN = UINT32_MAX,
    RENDERER_FRAMEBUFFER_SEPARATED = 0,
    RENDERER_FRAMEBUFFER_BLUR1,
    RENDERER_FRAMEBUFFER_BLUR2,
    RENDERER_FRAMEBUFFER_PEEL1,
    RENDERER_FRAMEBUFFER_PEEL2,
    RENDERER_FRAMEBUFFER_SENTINEL,
};

struct Renderer {
    MemoryArena arena;
    
    RendererSettings settings;
    
    GLuint standard_shader;
    GLuint view_location;
    GLuint projection_location;
    GLuint tex_location;
    
    GLuint render_framebuffer_shader;
    GLuint render_framebuffer_tex_location;
    GLuint render_framebuffer_vao;
    
    GLuint horizontal_gaussian_blur_shader;
    GLuint horizontal_gaussian_blur_tex_location;
    GLuint horizontal_gaussian_blur_target_width;
    GLuint vertical_gaussian_blur_shader;
    GLuint vertical_gaussian_blur_tex_location;
    GLuint vertical_gaussian_blur_target_height;
    
    RendererCommands commands;
    
    GLuint vertex_array;
    GLuint vertex_buffer;
    GLuint index_buffer;
    size_t max_texture_count;
    size_t texture_count;
    GLuint texture_array;
    
    GLuint framebuffer_ids[RENDERER_FRAMEBUFFER_SENTINEL];
    GLuint framebuffer_textures[RENDERER_FRAMEBUFFER_SENTINEL];
    GLuint framebuffer_depths[RENDERER_FRAMEBUFFER_SENTINEL];
    RendererFramebuffer framebuffers[RENDERER_FRAMEBUFFER_SENTINEL];
    
    u64 video_memory_used;
};

static void APIENTRY opengl_error_callback(GLenum source, GLenum type, GLenum id, GLenum severity, GLsizei length,
                                           const GLchar* message, const void *_) {
    (void)_;
    (void)length;
    if (severity == GL_DEBUG_SEVERITY_NOTIFICATION) return;
    
    char *source_str;
    switch(source) {
        case GL_DEBUG_SOURCE_API_ARB: {
		    source_str = "Calls to OpenGL API";
        } break;
        case GL_DEBUG_SOURCE_WINDOW_SYSTEM_ARB: {
		    source_str = "Calls to window-system API";
        } break;
        case GL_DEBUG_SOURCE_SHADER_COMPILER_ARB: {
		    source_str = "A compiler for shading language"; 
        } break;
        case GL_DEBUG_SOURCE_THIRD_PARTY_ARB: {
		    source_str = "Application associated with OpenGL"; 
        } break;
        case GL_DEBUG_SOURCE_APPLICATION_ARB: {
		    source_str = "Generated by user"; 
        } break;
        case GL_DEBUG_SOURCE_OTHER_ARB: {
		    source_str = "Other"; 
        } break;
        default: {
		    source_str = "Unknown"; 
        } break;
    }
    
    char *type_str;
    switch (type) {
        case GL_DEBUG_TYPE_ERROR_ARB: {
		    type_str = "ERROR"; 
        } break;
        case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR_ARB: {
		    type_str = "DEPRECATED_BEHAVIOR"; 
        } break;
        case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR_ARB: {
		    type_str = "UNDEFINED_BEHAVIOR"; 
        } break;
        case GL_DEBUG_TYPE_PORTABILITY_ARB: {
		    type_str = "PORTABILITY";
        } break;
        case GL_DEBUG_TYPE_PERFORMANCE_ARB: {
		    type_str = "PERFORMANCE"; 
        } break;
        case GL_DEBUG_TYPE_OTHER_ARB: {
		    type_str = "OTHER"; 
        } break;
        default: {
		    type_str = "UNKNOWN"; 
        } break;
    }
    
    char *severity_str;
    switch(severity) {
        case GL_DEBUG_SEVERITY_NOTIFICATION: {
		    severity_str = "NOTIFICATION"; 
        } break;
        case GL_DEBUG_SEVERITY_LOW_ARB: {
		    severity_str = "LOW"; 
        } break;
        case GL_DEBUG_SEVERITY_MEDIUM_ARB: {
		    severity_str = "MEDIUM"; 
        } break;
        case GL_DEBUG_SEVERITY_HIGH_ARB: {
		    severity_str = "HIGH"; 
        } break;
        default: {
		    severity_str = "UNKNOWN"; 
        } break;
    }
    fprintf(stderr, "OpenGL Error Callback\n<Source: %s, type: %s, Severity: %s, ID: %u>:::\n%s\n", source_str, type_str, severity_str, id, message);
}

static GLuint create_shader(const char *source) {
    GLuint vertex_shader = glCreateShader(GL_VERTEX_SHADER);
    GLuint fragment_shader = glCreateShader(GL_FRAGMENT_SHADER);
    const char *const vertex_source[] = { "#version 330\n", "#define VERTEX_SHADER\n", source };
    const char *const fragment_source[] = { "#version 330\n", "", source };
    glShaderSource(vertex_shader, ARRAY_SIZE(vertex_source), vertex_source, 0);
    glShaderSource(fragment_shader, ARRAY_SIZE(fragment_source), fragment_source, 0);
    glCompileShader(vertex_shader);
    glCompileShader(fragment_shader);
    
    GLint vertex_compiled, fragment_compiled;
    glGetShaderiv(vertex_shader, GL_COMPILE_STATUS, &vertex_compiled);
    glGetShaderiv(fragment_shader, GL_COMPILE_STATUS, &fragment_compiled);
    
    bool shader_failed = false;
    if (!(vertex_compiled && fragment_compiled)) {
        char shader_log[4096];
        if (!vertex_compiled) {
            glGetShaderInfoLog(vertex_shader, sizeof(shader_log), 0, shader_log);
            // fprintf(stderr, "[ERROR] OpenGL vertex shader compilation failed: %s\n", shader_log);
            shader_failed = true;
        }
        if (!fragment_compiled) {
            glGetShaderInfoLog(fragment_shader, sizeof(shader_log), 0, shader_log);
            // fprintf(stderr, "[ERROR] OpenGL fragment shader compilation failed: %s\n", shader_log);
            shader_failed = true;
        }
    }
    
    GLuint id = glCreateProgram();
    glAttachShader(id, vertex_shader);
    glAttachShader(id, fragment_shader);
    glLinkProgram(id);
    
    GLint link_success;
    glGetProgramiv(id, GL_LINK_STATUS, &link_success);
    if (!link_success) {
        char program_log[4096];
        glGetProgramInfoLog(id, sizeof(program_log), 0, program_log);
        // fprintf(stderr, "[ERROR] OpenGL shader compilation failed: %s\n", program_log);
        shader_failed = true;
    }    
    
    assert(!shader_failed);
    return id;
}

static void create_framebuffer(Renderer *renderer, u32 idx,
                               vec2 size, bool has_depth, bool filtered) {
    RendererFramebuffer result = {};
    result.has_depth = has_depth;
    result.size = size;
    
    GLuint id = renderer->framebuffer_ids[idx];
    GLuint tex_id = renderer->framebuffer_textures[idx];
    u32 mem = 0;
    
    glBindFramebuffer(GL_FRAMEBUFFER, id);
    glBindTexture(GL_TEXTURE_2D, tex_id);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, size.x, size.y, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0);
    GLenum filter = filtered ? GL_LINEAR : GL_NEAREST;
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, filter);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, filter);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, tex_id, 0);
    mem += size.x * size.y * 4;
    if (has_depth) {
        glGenRenderbuffers(1, renderer->framebuffer_depths + idx);
        GLuint depth_id = renderer->framebuffer_depths[idx];
        glBindRenderbuffer(GL_RENDERBUFFER, depth_id);
        glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, size.x, size.y);
        glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, depth_id);
        
        mem += size.x * size.y * 3;
    }
    assert(glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    
    renderer->video_memory_used += mem;
    result.video_memory = mem;
    renderer->framebuffers[idx] = result;
}

void init_renderer_for_settings(Renderer *renderer, RendererSettings settings) {
    renderer->texture_count = 0;
    GLenum min_filter, mag_filter;
    if (settings.filtered) {
        mag_filter = GL_LINEAR;
        if (settings.mipmapping) {
            min_filter = GL_LINEAR_MIPMAP_LINEAR;
        }  else {
            min_filter = GL_LINEAR;
        }
    } else {
        mag_filter = GL_NEAREST;
        if (settings.mipmapping) {
            min_filter = GL_NEAREST_MIPMAP_NEAREST;
        }  else {
            min_filter = GL_NEAREST;
        }
    }
    glBindTexture(GL_TEXTURE_2D_ARRAY, renderer->texture_array); 
    glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_MIN_FILTER, min_filter);
    glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_MAG_FILTER, mag_filter);
    glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glBindTexture(GL_TEXTURE_2D_ARRAY, 0);
    
#if 1
    size_t white_data_size = get_total_size_for_mips(RENDERER_TEXTURE_DIM, RENDERER_TEXTURE_DIM);
    TempMemory white_temp = begin_temp_memory(&renderer->arena);
    void *white_data = alloc(&renderer->arena, white_data_size);
    memset(white_data, 0xFF, white_data_size);
    renderer->commands.white_texture = renderer_create_texture_mipmaps(renderer, white_data, RENDERER_TEXTURE_DIM, RENDERER_TEXTURE_DIM);
    end_temp_memory(white_temp);
#else   
    // ...
    u32 white_data = 0xFFFFFFFF;
    renderer->commands.white_texture = renderer_create_texture_mipmaps(renderer, &white_data, 1, 1);
#endif   
    
    for (u32 i = 0; i < RENDERER_FRAMEBUFFER_SENTINEL; ++i) {
        renderer->video_memory_used -= renderer->framebuffers[i].video_memory;
    }
    glDeleteTextures(RENDERER_FRAMEBUFFER_SENTINEL, renderer->framebuffer_textures);
    glDeleteRenderbuffers(RENDERER_FRAMEBUFFER_SENTINEL, renderer->framebuffer_depths);
    glDeleteFramebuffers(RENDERER_FRAMEBUFFER_SENTINEL, renderer->framebuffer_ids);
    glGenTextures(RENDERER_FRAMEBUFFER_SENTINEL, renderer->framebuffer_textures);
    glGenFramebuffers(RENDERER_FRAMEBUFFER_SENTINEL, renderer->framebuffer_ids);
    
    vec2 size = settings.display_size;
    vec2 blur_size = size * 0.25f;
    b32 filter = settings.filtered;
    create_framebuffer(renderer, RENDERER_FRAMEBUFFER_SEPARATED, size, true, filter);
    create_framebuffer(renderer, RENDERER_FRAMEBUFFER_PEEL2, size, true, filter);
    create_framebuffer(renderer, RENDERER_FRAMEBUFFER_PEEL1, size, true, filter);
    create_framebuffer(renderer, RENDERER_FRAMEBUFFER_BLUR1, blur_size, false, filter);
    create_framebuffer(renderer, RENDERER_FRAMEBUFFER_BLUR2, blur_size, false, filter);
    
    renderer->settings = settings;
}

Renderer *renderer_init(RendererSettings settings) {
#define RENDERER_ARENA_SIZE MEGABYTES(256)
    Renderer *renderer = bootstrap_alloc_struct(Renderer, arena, RENDERER_ARENA_SIZE);
    
    glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS_ARB);
    glDebugMessageCallback(opengl_error_callback, 0);
    glDepthMask(GL_TRUE);
    glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
    glDepthFunc(GL_LEQUAL);
    glCullFace(GL_BACK);
    glFrontFace(GL_CCW);
    glProvokingVertex(GL_FIRST_VERTEX_CONVENTION);
    
#define MAX_QUADS_COUNT MEGABYTES(16)
#define MAX_VERTEX_COUNT (1 << 16)
#define MAX_INDEX_COUNT (MAX_VERTEX_COUNT / 2 * 3)
    renderer->commands.command_memory_size = MAX_QUADS_COUNT;
    renderer->commands.command_memory = (u8 *) alloc(&renderer->arena, MAX_QUADS_COUNT);
    renderer->commands.max_vertex_count = MAX_VERTEX_COUNT;
    renderer->commands.vertices = alloc_arr(&renderer->arena, MAX_VERTEX_COUNT, Vertex);
    renderer->commands.max_index_count = MAX_INDEX_COUNT;
    renderer->commands.indices = alloc_arr(&renderer->arena, MAX_INDEX_COUNT, RENDERER_INDEX_TYPE);
    
    const char *standard_shader_code = R"FOO(#ifdef VERTEX_SHADER       
layout(location = 0) in vec4 position;     
layout(location = 1) in vec2 uv;       
layout(location = 2) in vec3 n;        
layout(location = 3) in vec4 color;        
layout(location = 4) in int texture_index;     
       
out vec4 rect_color;       
out vec2 frag_uv;      
       
flat out int frag_texture_index;       

uniform mat4 view_matrix = mat4(1);     
uniform mat4 projection_matrix = mat4(1);

void main() {             
    vec4 world_space = position;       
    vec4 cam_space = view_matrix * world_space;
    vec4 clip_space = projection_matrix * cam_space;        
    gl_Position = clip_space;      
       
    rect_color = color;        
    frag_uv = uv;      
    frag_texture_index = texture_index;        
    
    float d = length(cam_space.xyz);
}      
#else 

in vec4 rect_color;        
in vec2 frag_uv;       
flat in int frag_texture_index;        
uniform sampler2DArray tex;        
out vec4 out_color;        
void main()        
{      
    vec3 array_uv = vec3(frag_uv.x, frag_uv.y, frag_texture_index);        
    vec4 texture_sample = texture(tex, array_uv);      
    
    out_color = texture_sample * rect_color;       
}      
#endif)FOO";
    renderer->standard_shader = create_shader(standard_shader_code);
    renderer->projection_location = glGetUniformLocation(renderer->standard_shader, "projection_matrix");
    assert(renderer->projection_location != (GLuint)-1);
    renderer->tex_location = glGetUniformLocation(renderer->standard_shader, "tex");
    assert(renderer->tex_location != (GLuint)-1);
    renderer->view_location = glGetUniformLocation(renderer->standard_shader, "view_matrix");
    assert(renderer->view_location != (GLuint)-1);
    const char *render_framebuffer_shader_code = R"FOO(#ifdef VERTEX_SHADER
layout(location = 0) in vec2 position;

out vec2 frag_uv;

void main() {
    gl_Position = vec4(position.x, position.y, 0.0, 1.0);
    frag_uv = (position + vec2(1)) * 0.5;
}
#else     

in vec2 frag_uv;
out vec4 out_color;

uniform sampler2D tex;

void main() {
    out_color = texture(tex, frag_uv);
}

#endif)FOO";
    renderer->render_framebuffer_shader = create_shader(render_framebuffer_shader_code);
    renderer->render_framebuffer_tex_location = glGetUniformLocation(renderer->render_framebuffer_shader, "tex");
    assert(renderer->render_framebuffer_tex_location != (GLuint)-1);
    
    const char *horizontal_gaussian_blur_shader_code = R"FOO(#ifdef VERTEX_SHADER
layout(location = 0) in vec2 position;

out vec2 blur_uvs[11];
uniform float target_width;

void main() {
    gl_Position = vec4(position.x, position.y, 0.0, 1.0);
    vec2 center_uv = (position + vec2(1)) * 0.5;
    float px_size = 1.0 / target_width;
    for (int i = -5; i <= 5; ++i) {
        blur_uvs[i + 5] = center_uv + vec2(px_size * i, 0);
    }
}

#else 

out vec4 out_color;
in vec2 blur_uvs[11];

uniform sampler2D tex;

void main() {
    out_color = vec4(0);
    out_color += texture(tex, blur_uvs[0]) * 0.0093;
    out_color += texture(tex, blur_uvs[1]) * 0.028002;
    out_color += texture(tex, blur_uvs[2]) * 0.065984;
    out_color += texture(tex, blur_uvs[3]) * 0.121703;
    out_color += texture(tex, blur_uvs[4]) * 0.175713;
    out_color += texture(tex, blur_uvs[5]) * 0.198596;
    out_color += texture(tex, blur_uvs[6]) * 0.175713;
    out_color += texture(tex, blur_uvs[7]) * 0.121703;
    out_color += texture(tex, blur_uvs[8]) * 0.065984;
    out_color += texture(tex, blur_uvs[9]) * 0.028002;
    out_color += texture(tex, blur_uvs[10]) * 0.0093;
}

#endif)FOO";
    renderer->horizontal_gaussian_blur_shader = create_shader(horizontal_gaussian_blur_shader_code);
    renderer->horizontal_gaussian_blur_tex_location = glGetUniformLocation(renderer->horizontal_gaussian_blur_shader, "tex");
    renderer->horizontal_gaussian_blur_target_width = glGetUniformLocation(renderer->horizontal_gaussian_blur_shader, "target_width");
    assert(renderer->horizontal_gaussian_blur_tex_location != (GLuint)-1);
    assert(renderer->horizontal_gaussian_blur_target_width != (GLuint)-1);
    
    const char *vertical_gaussian_blur_shader_code = R"FOO(#ifdef VERTEX_SHADER
layout(location = 0) in vec2 position;

out vec2 blur_uvs[11];
uniform float target_height;

void main() {
    gl_Position = vec4(position.x, position.y, 0.0, 1.0);
    vec2 center_uv = (position + vec2(1)) * 0.5;
    float px_size = 1.0 / target_height;
    for (int i = -5; i <= 5; ++i) {
        blur_uvs[i + 5] = center_uv + vec2(0, px_size * i);
    }
}

#else 

out vec4 out_color;
in vec2 blur_uvs[11];

uniform sampler2D tex;

void main() {
    out_color = vec4(0);
    out_color += texture(tex, blur_uvs[0]) * 0.0093;
    out_color += texture(tex, blur_uvs[1]) * 0.028002;
    out_color += texture(tex, blur_uvs[2]) * 0.065984;
    out_color += texture(tex, blur_uvs[3]) * 0.121703;
    out_color += texture(tex, blur_uvs[4]) * 0.175713;
    out_color += texture(tex, blur_uvs[5]) * 0.198596;
    out_color += texture(tex, blur_uvs[6]) * 0.175713;
    out_color += texture(tex, blur_uvs[7]) * 0.121703;
    out_color += texture(tex, blur_uvs[8]) * 0.065984;
    out_color += texture(tex, blur_uvs[9]) * 0.028002;
    out_color += texture(tex, blur_uvs[10]) * 0.0093;
}

#endif)FOO";
    renderer->vertical_gaussian_blur_shader = create_shader(vertical_gaussian_blur_shader_code);
    renderer->vertical_gaussian_blur_tex_location = glGetUniformLocation(renderer->vertical_gaussian_blur_shader, "tex");
    renderer->vertical_gaussian_blur_target_height = glGetUniformLocation(renderer->vertical_gaussian_blur_shader, "target_height");
    assert(renderer->vertical_gaussian_blur_tex_location != (GLuint)-1);
    assert(renderer->vertical_gaussian_blur_target_height != (GLuint)-1);
    
    // Generate vertex arrays
    glGenVertexArrays(1, &renderer->render_framebuffer_vao);
    glBindVertexArray(renderer->render_framebuffer_vao);
    GLuint renderer_framebuffer_vbo;
    f32 render_framebuffer_data[] = {
        -1.0f, -1.0f, 
        -1.0f, 1.0f, 
        1.0f, -1.0f, 
        1.0f, 1.0f, 
    };
    glGenBuffers(1, &renderer_framebuffer_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, renderer_framebuffer_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(render_framebuffer_data), render_framebuffer_data, GL_STATIC_DRAW);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 8, (void *)0);
    glEnableVertexAttribArray(0);
    glBindVertexArray(0);
    
    glGenVertexArrays(1, &renderer->vertex_array);
    glBindVertexArray(renderer->vertex_array);
    
    glGenBuffers(1, &renderer->vertex_buffer);
    glBindBuffer(GL_ARRAY_BUFFER, renderer->vertex_buffer);
    glBufferData(GL_ARRAY_BUFFER, renderer->commands.max_vertex_count * sizeof(Vertex), 0, GL_STREAM_DRAW);
    renderer->video_memory_used += renderer->commands.max_vertex_count * sizeof(Vertex);
    
    glGenBuffers(1, &renderer->index_buffer);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, renderer->index_buffer);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, renderer->commands.max_index_count * sizeof(RENDERER_INDEX_TYPE), 0, GL_STREAM_DRAW);
    renderer->video_memory_used += renderer->commands.max_index_count * sizeof(RENDERER_INDEX_TYPE);
    
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)STRUCT_OFFSET(Vertex, p));
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)STRUCT_OFFSET(Vertex, uv));
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(2, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)STRUCT_OFFSET(Vertex, n));
    glEnableVertexAttribArray(2);
    glVertexAttribPointer(3, 4, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void *)STRUCT_OFFSET(Vertex, c));
    glEnableVertexAttribArray(3);
    glVertexAttribIPointer(4, 1, GL_UNSIGNED_SHORT, sizeof(Vertex), (void *)STRUCT_OFFSET(Vertex, tex));
    glEnableVertexAttribArray(4);
    
    glBindVertexArray(0);
    
#define MAX_TEXTURE_COUNT 256
    renderer->max_texture_count = MAX_TEXTURE_COUNT;
    glGenTextures(1, &renderer->texture_array);
    glBindTexture(GL_TEXTURE_2D_ARRAY, renderer->texture_array);
    ITERATE(iter, iterate_mips(RENDERER_TEXTURE_DIM, RENDERER_TEXTURE_DIM)) {
        glTexImage3D(GL_TEXTURE_2D_ARRAY, iter.level, GL_RGBA8, 
                     iter.width, iter.height, MAX_TEXTURE_COUNT,
                     0, GL_RGBA, GL_UNSIGNED_BYTE, 0);        
        renderer->video_memory_used += iter.width * iter.height * 4;
    }
    init_renderer_for_settings(renderer, settings);
    return renderer;
}

RendererCommands *renderer_begin_frame(Renderer *renderer) {
    RendererCommands *commands = &renderer->commands;
    commands->command_memory_used = 0;
    commands->vertex_count = 0;
    commands->index_count = 0;
    commands->last_header = 0;
    commands->last_setup = 0;
    return commands;
}

static void bind_framebuffer(Renderer *renderer, u32 id, bool clear = false) {
    b32 has_depth = false;
    if (id == RENDERER_FRAMEBUFFER_MAIN) {
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        glViewport(0, 0, renderer->settings.display_size.x, renderer->settings.display_size.y);
        has_depth = true;
    } else {
        RendererFramebuffer *framebuffer = renderer->framebuffers + id;
        glBindFramebuffer(GL_FRAMEBUFFER, renderer->framebuffer_ids[id]);
        glViewport(0, 0, framebuffer->size.x, framebuffer->size.y);
        has_depth = framebuffer->has_depth;
    }
    
    if (clear) {
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        u32 flags = GL_COLOR_BUFFER_BIT;
        if (has_depth) {
            flags |= GL_DEPTH_BUFFER_BIT;
        }
        glClear(flags);
    }
    
}

static void blit_framebuffer(Renderer *renderer, u32 from, u32 to, bool clear = false) {
    bind_framebuffer(renderer, to, clear);
    
    glDisable(GL_DEPTH_TEST);
    glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
    glUseProgram(renderer->render_framebuffer_shader);
    glBindVertexArray(renderer->render_framebuffer_vao);
    glBindTexture(GL_TEXTURE_2D, renderer->framebuffer_textures[from]);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    glBindTexture(GL_TEXTURE_2D, 0);
    glBindVertexArray(0);
    glUseProgram(0);
    glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
    glEnable(GL_DEPTH_TEST);
}

void renderer_end_frame(Renderer *renderer) {
    TIMED_FUNCTION();
    // Upload data from vertex array to OpenGL buffers
    glBindVertexArray(renderer->vertex_array);
    glBufferSubData(GL_ARRAY_BUFFER, 0, renderer->commands.vertex_count * sizeof(Vertex), renderer->commands.vertices);
    glBufferSubData(GL_ELEMENT_ARRAY_BUFFER, 0, renderer->commands.index_count * sizeof(RENDERER_INDEX_TYPE), renderer->commands.indices);
    glBindVertexArray(0);
    
    glEnable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
    glActiveTexture(GL_TEXTURE0);
    
    // This is local renderer state
    RendererSetup *current_setup = 0;
    u32 current_framebuffer = RENDERER_FRAMEBUFFER_MAIN;
    bind_framebuffer(renderer, current_framebuffer, true);
    
    u8 *cursor = renderer->commands.command_memory;
    u8 *commands_bound = renderer->commands.command_memory + renderer->commands.command_memory_used;
    
    u32 DEBUG_draw_call_count = 0;
    while (cursor < commands_bound) {
        RendererCommandHeader *header = (RendererCommandHeader *)cursor;
        cursor += sizeof(*header);
        switch (header->type) {
            case RENDERER_COMMAND_QUADS: {
                RendererCommandQuads *quads = (RendererCommandQuads *)cursor;
                cursor += sizeof(*quads);
                
                assert(current_setup);
                glUseProgram(renderer->standard_shader);
                glBindVertexArray(renderer->vertex_array);
                glUniformMatrix4fv(renderer->view_location, 1, false, current_setup->view.value_ptr());
                glUniformMatrix4fv(renderer->projection_location, 1, false, current_setup->projection.value_ptr());
                glBindTexture(GL_TEXTURE_2D_ARRAY, renderer->texture_array);
                glDrawElementsBaseVertex(GL_TRIANGLES, 6 * quads->quad_count, GL_INDEX_TYPE, (void *)(sizeof(RENDERER_INDEX_TYPE) * quads->index_array_offset), quads->vertex_array_offset);
                glBindTexture(GL_TEXTURE_2D_ARRAY, 0);
                glBindVertexArray(0);
                glUseProgram(0);
                
                ++DEBUG_draw_call_count;
            } break;
            case RENDERER_COMMAND_BLUR: {
                assert(current_framebuffer == RENDERER_FRAMEBUFFER_SEPARATED);
                
                bind_framebuffer(renderer, RENDERER_FRAMEBUFFER_BLUR1, true);
                
                glUseProgram(renderer->horizontal_gaussian_blur_shader);
                glBindVertexArray(renderer->render_framebuffer_vao);
                glUniform1f(renderer->horizontal_gaussian_blur_target_width, renderer->framebuffers[RENDERER_FRAMEBUFFER_BLUR2].size.x);
                glBindTexture(GL_TEXTURE_2D, renderer->framebuffer_textures[RENDERER_FRAMEBUFFER_SEPARATED]);
                glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
                glBindVertexArray(0);
                glUseProgram(0);
                glBindFramebuffer(GL_FRAMEBUFFER, 0);
                
                bind_framebuffer(renderer, RENDERER_FRAMEBUFFER_BLUR2, true);
                
                glUseProgram(renderer->vertical_gaussian_blur_shader);
                glBindVertexArray(renderer->render_framebuffer_vao);
                glUniform1f(renderer->vertical_gaussian_blur_target_height, renderer->framebuffers[RENDERER_FRAMEBUFFER_BLUR2].size.y);
                glBindTexture(GL_TEXTURE_2D, renderer->framebuffer_textures[RENDERER_FRAMEBUFFER_BLUR1]);
                glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
                glBindVertexArray(0);
                glUseProgram(0);
                glBindFramebuffer(GL_FRAMEBUFFER, 0);
                
                blit_framebuffer(renderer, RENDERER_FRAMEBUFFER_BLUR2, RENDERER_FRAMEBUFFER_SEPARATED, true);
                
                DEBUG_draw_call_count += 3;
            } break;
            case RENDERER_COMMAND_BEGIN_SEPARATED: {
                current_framebuffer = RENDERER_FRAMEBUFFER_SEPARATED;
                bind_framebuffer(renderer, current_framebuffer, true);
            } break;
            case RENDERER_COMMAND_END_SEPARATED: {
                current_framebuffer = RENDERER_FRAMEBUFFER_MAIN;
                blit_framebuffer(renderer, RENDERER_FRAMEBUFFER_SEPARATED, RENDERER_FRAMEBUFFER_MAIN);
                ++DEBUG_draw_call_count;
            } break;
            case RENDERER_COMMAND_SET_SETUP: {
                RendererSetup *setup = (RendererSetup *)cursor;
                cursor += sizeof(*setup);
                
                current_setup = setup;
            } break;
            INVALID_DEFAULT_CASE;
        }
    }
    
    assert(current_framebuffer == RENDERER_FRAMEBUFFER_MAIN);
    
    {DEBUG_VALUE_BLOCK("Renderer")
            DEBUG_VALUE(renderer->video_memory_used >> 20, "Video memory used");
        DEBUG_VALUE(renderer->texture_count, "Texture count");
        DEBUG_VALUE((f32)renderer->commands.index_count / renderer->commands.max_index_count * 100, "Index buffer");
        DEBUG_VALUE((f32)renderer->commands.vertex_count / renderer->commands.max_vertex_count * 100, "Vertex buffer");
        DEBUG_VALUE(DEBUG_draw_call_count, "Draw call count");
    }
}

Texture renderer_create_texture_mipmaps(Renderer *renderer, void *data, u32 width, u32 height) {
    assert(width <= RENDERER_TEXTURE_DIM && height <= RENDERER_TEXTURE_DIM);
    Texture tex;
    assert(renderer->texture_count + 1 < renderer->max_texture_count);
    tex.index = (u32)renderer->texture_count++;
    tex.width  = (u16)width;
    tex.height = (u16)height;
    assert(tex.width == width && tex.height == height);
    glBindTexture(GL_TEXTURE_2D_ARRAY, renderer->texture_array);
    ITERATE(iter, iterate_mips(width, height)) {
        glTexSubImage3D(GL_TEXTURE_2D_ARRAY, iter.level, 0, 0,
                        tex.index, iter.width, iter.height, 1,
                        GL_RGBA, GL_UNSIGNED_BYTE, (u32 *)data + iter.pixel_offset);    
    }
    glBindTexture(GL_TEXTURE_2D_ARRAY, 0);
    return tex;
}


RendererSettings *get_current_settings(Renderer *renderer) {
    return &renderer->settings;
}